import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "@tanstack/react-router";
import { CheckCircle2, ChevronLeft, ChevronRight, HeartHandshake } from "lucide-react";
import { Button } from "@/components/ui/button";
import { MotionCard } from "@/components/motion-card";
import { authService, patientService } from "@/lib/api";
import { ACP_SECTIONS, completedSectionKeys, type AcpSectionKey } from "@/lib/acp-workflow";
import { toast } from "sonner";

const isSection = (value: string): value is AcpSectionKey => ACP_SECTIONS.some((section) => section.key === value);
const fieldClass = "mt-1 h-10 w-full rounded-lg border border-border bg-surface px-3 text-sm outline-none focus:ring-2 focus:ring-primary/30";
const labelClass = "text-xs font-medium text-muted-foreground";

export function AcpWorkflow({ section }: { section: string }) {
  const navigate = useNavigate(); const queryClient = useQueryClient();
  const { data: profile, isLoading: profileLoading } = useQuery({ queryKey: ["patientProfile"], queryFn: patientService.getProfile });
  const patientId = profile?.patient_id;
  const { data: acp } = useQuery({ queryKey: ["patientAcp", patientId], queryFn: () => patientService.getACP(patientId), enabled: !!patientId, retry: false });
  const { data: dhrs = [] } = useQuery({ queryKey: ["patientDhrs", patientId], queryFn: () => patientService.getDHRs(patientId), enabled: !!patientId });
  const completed = completedSectionKeys(profile, acp, dhrs);
  const activeKey: AcpSectionKey = isSection(section) ? section : "personal";
  const activeIndex = ACP_SECTIONS.findIndex((item) => item.key === activeKey);
  const go = (key: AcpSectionKey) => navigate({ to: "/patient-dashboard/acp/$section", params: { section: key } });
  const refresh = () => { queryClient.invalidateQueries({ queryKey: ["patientProfile"] }); queryClient.invalidateQueries({ queryKey: ["patientAcp", patientId] }); queryClient.invalidateQueries({ queryKey: ["patientDhrs", patientId] }); };
  useEffect(() => {
    if (!profileLoading && !patientId && section !== "profile") {
      navigate({ to: "/patient-dashboard/acp/$section", params: { section: "profile" } });
    }
  }, [navigate, patientId, profileLoading, section]);
  if (profileLoading || (!patientId && section !== "profile")) return <p className="text-sm text-muted-foreground">Preparing your ACP…</p>;
  if (!patientId) return <CreatePatientProfile onCreated={async () => { await queryClient.refetchQueries({ queryKey: ["patientProfile"] }); navigate({ to: "/patient-dashboard/acp/$section", params: { section: "personal" } }); }} />;
  return <div className="max-w-4xl"><header><h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">Advance Care Planning</h1><p className="mt-1 text-sm text-muted-foreground">Complete each section at your own pace. Your progress is saved securely.</p></header>
    <MotionCard className="mt-6 p-4"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{ACP_SECTIONS.map((item, index) => <button type="button" key={item.key} onClick={() => go(item.key)} className="text-left"><div className={`flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold ${completed.includes(item.key) ? "bg-primary text-primary-foreground" : index === activeIndex ? "border-2 border-primary text-primary" : "bg-surface text-muted-foreground"}`}>{completed.includes(item.key) ? <CheckCircle2 className="h-4 w-4" /> : index + 1}</div><p className="mt-2 text-xs font-medium text-foreground">{item.title}</p></button>)}</div></MotionCard>
    <MotionCard className="mt-6"><div className="flex items-center gap-3 border-b border-border pb-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><HeartHandshake className="h-5 w-5" /></div><div><h2 className="font-bold">{ACP_SECTIONS[activeIndex].title}</h2><p className="text-xs text-muted-foreground">Step {activeIndex + 1} of {ACP_SECTIONS.length}</p></div></div>
      {activeKey === "personal" && <PersonalForm profile={profile} patientId={patientId} onSaved={() => { refresh(); go("medical"); }} />}
      {activeKey === "medical" && <MedicalForm acp={acp} patientId={patientId} onSaved={() => { refresh(); go("end-of-life"); }} />}
      {activeKey === "end-of-life" && <EndOfLifeForm acp={acp} patientId={patientId} onSaved={() => { refresh(); go("proxy"); }} />}
      {activeKey === "proxy" && <ProxyForm patientId={patientId} dhrs={dhrs} onSaved={() => { refresh(); go("donation"); }} />}
      {activeKey === "donation" && <DonationForm acp={acp} patientId={patientId} onSaved={() => { refresh(); go("review"); }} />}
      {activeKey === "review" && <ReviewForm patientId={patientId} profile={profile} acp={acp} dhrs={dhrs} completed={completed} onSaved={() => { refresh(); toast.success("Your ACP has been completed. Add two witnesses to generate your AMD."); navigate({ to: "/patient-dashboard/documents" }); }} />}
      <div className="mt-6 flex justify-between border-t border-border pt-4"><Button variant="outline" disabled={activeIndex === 0} onClick={() => go(ACP_SECTIONS[activeIndex - 1].key)}><ChevronLeft className="mr-1 h-4 w-4" />Back</Button><span className="self-center text-xs text-muted-foreground">Saved information remains available when you return.</span></div>
    </MotionCard></div>;
}

function CreatePatientProfile({ onCreated }: { onCreated: () => void | Promise<void> }) {
  const currentUser = authService.getCurrentUser();
  const [form, setForm] = useState({ phone: "", preferred_language: "English", address: "" });
  const create = useMutation({
    mutationFn: () => {
      if (!currentUser?.user_id) throw new Error("Your account details are unavailable. Please sign in again.");
      return patientService.createProfile({ user_id: currentUser.user_id, ...form });
    },
    onSuccess: onCreated,
    onError: (error: Error) => toast.error(error.message),
  });
  return <div className="max-w-2xl"><header><h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">Create Patient Profile</h1><p className="mt-1 text-sm text-muted-foreground">A few details are needed before you can begin Advance Care Planning.</p></header><MotionCard className="mt-6"><form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><label className={labelClass}>Phone number<input required pattern="[0-9+ ()-]{10,20}" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} className={fieldClass} /></label><label className={labelClass}>Preferred language<select value={form.preferred_language} onChange={(event) => setForm({ ...form, preferred_language: event.target.value })} className={fieldClass}><option>English</option><option>Hindi</option><option>Kannada</option></select></label><label className={`sm:col-span-2 ${labelClass}`}>Address<textarea required value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} className="mt-1 min-h-20 w-full rounded-lg border border-border bg-surface p-3 text-sm outline-none focus:ring-2 focus:ring-primary/30" /></label><div className="sm:col-span-2 mt-2 flex justify-end"><Button type="submit" disabled={create.isPending}>{create.isPending ? "Creating…" : "Create profile and continue"}<ChevronRight className="ml-2 h-4 w-4" /></Button></div></form></MotionCard></div>;
}
function FormActions({ pending, label = "Save and continue" }: { pending: boolean; label?: string }) { return <div className="mt-6 flex justify-end"><Button type="submit" disabled={pending}>{pending ? "Saving…" : <><span>{label}</span><ChevronRight className="ml-2 h-4 w-4" /></>}</Button></div>; }
function PersonalForm({ profile, patientId, onSaved }: any) { const [form, setForm] = useState({ phone: "", preferred_language: "English", address: "", beliefs_values: "" }); useEffect(() => setForm({ phone: profile?.phone || "", preferred_language: profile?.preferred_language || "English", address: profile?.address || profile?.permanent_address || profile?.current_address || "", beliefs_values: profile?.beliefs_values || "" }), [profile]); const save = useMutation({ mutationFn: () => patientService.updateProfile(patientId, form), onSuccess: onSaved, onError: (e: Error) => toast.error(e.message) }); return <form className="mt-6 grid gap-4 sm:grid-cols-2" onSubmit={(e) => { e.preventDefault(); save.mutate(); }}><label className={labelClass}>Phone number<input required pattern="[0-9+ ()-]{10,20}" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} className={fieldClass} /></label><label className={labelClass}>Preferred language<select value={form.preferred_language} onChange={(e) => setForm({ ...form, preferred_language: e.target.value })} className={fieldClass}><option>English</option><option>Hindi</option><option>Kannada</option></select></label><label className={`sm:col-span-2 ${labelClass}`}>Address<textarea required value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} className="mt-1 min-h-20 w-full rounded-lg border border-border bg-surface p-3 text-sm outline-none focus:ring-2 focus:ring-primary/30" /></label><label className={`sm:col-span-2 ${labelClass}`}>Personal values or beliefs (optional)<textarea value={form.beliefs_values} onChange={(e) => setForm({ ...form, beliefs_values: e.target.value })} className="mt-1 min-h-20 w-full rounded-lg border border-border bg-surface p-3 text-sm outline-none focus:ring-2 focus:ring-primary/30" /></label><div className="sm:col-span-2"><FormActions pending={save.isPending} /></div></form>; }
function MedicalForm({ acp, patientId, onSaved }: any) { const keys = [["cpr_preference", "CPR"], ["ventilator_preference", "Ventilator"], ["dialysis_preference", "Dialysis"], ["chemotherapy_preference", "Chemotherapy"], ["radiotherapy_preference", "Radiotherapy"], ["surgery_preference", "Surgery"]] as const; const [form, setForm] = useState<any>({}); useEffect(() => setForm(Object.fromEntries(keys.map(([key]) => [key, (acp?.[key] && acp[key] !== "NOT SPECIFIED") ? acp[key] : ""]))), [acp]); const save = useMutation({ mutationFn: () => patientService.updateACP(patientId, form), onSuccess: onSaved, onError: (e: Error) => toast.error(e.message) }); return <form className="mt-6 grid gap-4 sm:grid-cols-2" onSubmit={(e) => { e.preventDefault(); save.mutate(); }}>{keys.map(([key, label]) => <label key={key} className={labelClass}>{label}<select required value={form[key] || ""} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className={fieldClass}><option value="">Choose an option</option><option value="WANT">I want this treatment</option><option value="DO NOT WANT">I do not want this treatment</option></select></label>)}<div className="sm:col-span-2"><FormActions pending={save.isPending} /></div></form>; }
function EndOfLifeForm({ acp, patientId, onSaved }: any) { const [form, setForm] = useState({ pain_management: "", preferred_place_of_care: "", preferred_hospital: "", additional_wishes: "" }); useEffect(() => setForm({ pain_management: acp?.pain_management || "", preferred_place_of_care: acp?.preferred_place_of_care || "", preferred_hospital: acp?.preferred_hospital || "", additional_wishes: acp?.additional_wishes || "" }), [acp]); const save = useMutation({ mutationFn: () => patientService.updateACP(patientId, form), onSuccess: onSaved, onError: (e: Error) => toast.error(e.message) }); return <form className="mt-6 grid gap-4 sm:grid-cols-2" onSubmit={(e) => { e.preventDefault(); save.mutate(); }}><label className={labelClass}>Preferred place of care<select required value={form.preferred_place_of_care} onChange={(e) => setForm({ ...form, preferred_place_of_care: e.target.value })} className={fieldClass}><option value="">Choose a place</option><option>Home</option><option>Hospital</option><option>Hospice</option></select></label><label className={labelClass}>Preferred hospital (optional)<input value={form.preferred_hospital} onChange={(e) => setForm({ ...form, preferred_hospital: e.target.value })} className={fieldClass} /></label><label className={`sm:col-span-2 ${labelClass}`}>Pain and comfort-care wishes<textarea required value={form.pain_management} onChange={(e) => setForm({ ...form, pain_management: e.target.value })} className="mt-1 min-h-20 w-full rounded-lg border border-border bg-surface p-3 text-sm outline-none focus:ring-2 focus:ring-primary/30" /></label><label className={`sm:col-span-2 ${labelClass}`}>Additional wishes (optional)<textarea value={form.additional_wishes} onChange={(e) => setForm({ ...form, additional_wishes: e.target.value })} className="mt-1 min-h-20 w-full rounded-lg border border-border bg-surface p-3 text-sm outline-none focus:ring-2 focus:ring-primary/30" /></label><div className="sm:col-span-2"><FormActions pending={save.isPending} /></div></form>; }
function ProxyForm({ patientId, dhrs, onSaved }: any) {
  const primaryDhr = dhrs[0];
  const [form, setForm] = useState({ full_name: "", relationship: "", email_primary: "", mobile_primary: "" });
  useEffect(() => setForm({
    full_name: primaryDhr?.full_name || "",
    relationship: primaryDhr?.relationship || "",
    email_primary: primaryDhr?.email_primary || "",
    mobile_primary: primaryDhr?.mobile_primary || "",
  }), [primaryDhr]);
  const save = useMutation({
    mutationFn: () => primaryDhr
      ? patientService.updateDHR(primaryDhr.id, form)
      : patientService.createDHR({ patient_id: patientId, ...form }),
    onSuccess: onSaved,
    onError: (e: Error) => toast.error(e.message),
  });
  return <form className="mt-6 grid gap-4 sm:grid-cols-2" onSubmit={(e) => { e.preventDefault(); save.mutate(); }}>
    {primaryDhr && <p className="sm:col-span-2 rounded-lg bg-primary/5 p-3 text-sm text-primary">Primary representative: {primaryDhr.full_name}. Update these details when they change.</p>}
    <label className={labelClass}>Full name<input required value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} className={fieldClass} /></label>
    <label className={labelClass}>Relationship<input required value={form.relationship} onChange={(e) => setForm({ ...form, relationship: e.target.value })} className={fieldClass} /></label>
    <label className={labelClass}>Email<input required type="email" value={form.email_primary} onChange={(e) => setForm({ ...form, email_primary: e.target.value })} className={fieldClass} /></label>
    <label className={labelClass}>Mobile number<input required pattern="[0-9+ ()-]{10,20}" value={form.mobile_primary} onChange={(e) => setForm({ ...form, mobile_primary: e.target.value })} className={fieldClass} /></label>
    <div className="sm:col-span-2"><FormActions pending={save.isPending} /></div>
  </form>;
}function DonationForm({ acp, patientId, onSaved }: any) { const [form, setForm] = useState({ organ_donation: "", body_donation: "", last_rites: "" }); useEffect(() => setForm({ organ_donation: acp?.organ_donation === "NOT SPECIFIED" ? "" : (acp?.organ_donation || ""), body_donation: acp?.body_donation === "NOT SPECIFIED" ? "" : (acp?.body_donation || ""), last_rites: acp?.last_rites || "" }), [acp]); const save = useMutation({ mutationFn: () => patientService.updateACP(patientId, form), onSuccess: onSaved, onError: (e: Error) => toast.error(e.message) }); return <form className="mt-6 grid gap-4 sm:grid-cols-2" onSubmit={(e) => { e.preventDefault(); save.mutate(); }}>{[["organ_donation", "Organ donation"], ["body_donation", "Body donation"]].map(([key, label]) => <label key={key} className={labelClass}>{label}<select required value={(form as any)[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className={fieldClass}><option value="">Choose an option</option><option value="YES">Yes</option><option value="NO">No</option></select></label>)}<label className={`sm:col-span-2 ${labelClass}`}>Last rites or funeral wishes (optional)<textarea value={form.last_rites} onChange={(e) => setForm({ ...form, last_rites: e.target.value })} className="mt-1 min-h-20 w-full rounded-lg border border-border bg-surface p-3 text-sm outline-none focus:ring-2 focus:ring-primary/30" /></label><div className="sm:col-span-2"><FormActions pending={save.isPending} /></div></form>; }
function ReviewForm({ patientId, profile, acp, dhrs, completed, onSaved }: any) { const [confirmed, setConfirmed] = useState(false); const save = useMutation({ mutationFn: () => patientService.updateACP(patientId, { is_completed: true }), onSuccess: onSaved, onError: (e: Error) => toast.error(e.message) }); const ready = ACP_SECTIONS.slice(0, 5).every((item) => completed.includes(item.key)); return <div className="mt-6"><div className="rounded-xl bg-surface p-4 text-sm"><p className="font-semibold">Review your plan</p><p className="mt-2 text-muted-foreground">Personal details: {profile?.full_name || "Saved"} · Representative: {dhrs[0]?.full_name || "Not added"}</p><p className="mt-1 text-muted-foreground">Medical preferences and end-of-life wishes are stored in your ACP record.</p></div><label className="mt-5 flex items-start gap-2 text-sm"><input required type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} className="mt-1" /><span>I confirm these choices reflect my current wishes and can be reviewed with my care team.</span></label>{!ready && <p className="mt-3 text-sm text-warning">Please complete the previous sections before confirming your ACP.</p>}<div className="mt-6 flex justify-end"><Button disabled={!confirmed || !ready || save.isPending} onClick={() => save.mutate()}>{save.isPending ? "Saving…" : "Complete ACP"}</Button></div></div>; }