/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientDashboardRouteImport } from './routes/patient-dashboard'
import { Route as DoctorDashboardRouteImport } from './routes/doctor-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientDashboardIndexRouteImport } from './routes/patient-dashboard.index'
import { Route as PatientDashboardSettingsRouteImport } from './routes/patient-dashboard.settings'
import { Route as PatientDashboardDocumentsRouteImport } from './routes/patient-dashboard.documents'
import { Route as PatientDashboardChatRouteImport } from './routes/patient-dashboard.chat'
import { Route as DoctorDashboardSettingsRouteImport } from './routes/doctor-dashboard.settings'
import { Route as DoctorDashboardReviewsRouteImport } from './routes/doctor-dashboard.reviews'
import { Route as DoctorDashboardPatientsRouteImport } from './routes/doctor-dashboard.patients'
import { Route as DoctorDashboardAnalyticsRouteImport } from './routes/doctor-dashboard.analytics'
import { Route as PatientDashboardAcpSectionRouteImport } from './routes/patient-dashboard.acp.$section'

const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/patient-dashboard',
  path: '/patient-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor-dashboard',
  path: '/doctor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardIndexRoute = PatientDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientDashboardRoute,
} as any)
const PatientDashboardSettingsRoute =
  PatientDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => PatientDashboardRoute,
  } as any)
const PatientDashboardDocumentsRoute =
  PatientDashboardDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => PatientDashboardRoute,
  } as any)
const PatientDashboardChatRoute = PatientDashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PatientDashboardRoute,
} as any)
const DoctorDashboardSettingsRoute = DoctorDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DoctorDashboardRoute,
} as any)
const DoctorDashboardReviewsRoute = DoctorDashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DoctorDashboardRoute,
} as any)
const DoctorDashboardPatientsRoute = DoctorDashboardPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorDashboardRoute,
} as any)
const DoctorDashboardAnalyticsRoute =
  DoctorDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DoctorDashboardRoute,
  } as any)
const PatientDashboardAcpSectionRoute =
  PatientDashboardAcpSectionRouteImport.update({
    id: '/acp/$section',
    path: '/acp/$section',
    getParentRoute: () => PatientDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor-dashboard': typeof DoctorDashboardRouteWithChildren
  '/patient-dashboard': typeof PatientDashboardRouteWithChildren
  '/doctor-dashboard/analytics': typeof DoctorDashboardAnalyticsRoute
  '/doctor-dashboard/patients': typeof DoctorDashboardPatientsRoute
  '/doctor-dashboard/reviews': typeof DoctorDashboardReviewsRoute
  '/doctor-dashboard/settings': typeof DoctorDashboardSettingsRoute
  '/patient-dashboard/chat': typeof PatientDashboardChatRoute
  '/patient-dashboard/documents': typeof PatientDashboardDocumentsRoute
  '/patient-dashboard/settings': typeof PatientDashboardSettingsRoute
  '/patient-dashboard/': typeof PatientDashboardIndexRoute
  '/patient-dashboard/acp/$section': typeof PatientDashboardAcpSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctor-dashboard': typeof DoctorDashboardRouteWithChildren
  '/doctor-dashboard/analytics': typeof DoctorDashboardAnalyticsRoute
  '/doctor-dashboard/patients': typeof DoctorDashboardPatientsRoute
  '/doctor-dashboard/reviews': typeof DoctorDashboardReviewsRoute
  '/doctor-dashboard/settings': typeof DoctorDashboardSettingsRoute
  '/patient-dashboard/chat': typeof PatientDashboardChatRoute
  '/patient-dashboard/documents': typeof PatientDashboardDocumentsRoute
  '/patient-dashboard/settings': typeof PatientDashboardSettingsRoute
  '/patient-dashboard': typeof PatientDashboardIndexRoute
  '/patient-dashboard/acp/$section': typeof PatientDashboardAcpSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor-dashboard': typeof DoctorDashboardRouteWithChildren
  '/patient-dashboard': typeof PatientDashboardRouteWithChildren
  '/doctor-dashboard/analytics': typeof DoctorDashboardAnalyticsRoute
  '/doctor-dashboard/patients': typeof DoctorDashboardPatientsRoute
  '/doctor-dashboard/reviews': typeof DoctorDashboardReviewsRoute
  '/doctor-dashboard/settings': typeof DoctorDashboardSettingsRoute
  '/patient-dashboard/chat': typeof PatientDashboardChatRoute
  '/patient-dashboard/documents': typeof PatientDashboardDocumentsRoute
  '/patient-dashboard/settings': typeof PatientDashboardSettingsRoute
  '/patient-dashboard/': typeof PatientDashboardIndexRoute
  '/patient-dashboard/acp/$section': typeof PatientDashboardAcpSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctor-dashboard'
    | '/patient-dashboard'
    | '/doctor-dashboard/analytics'
    | '/doctor-dashboard/patients'
    | '/doctor-dashboard/reviews'
    | '/doctor-dashboard/settings'
    | '/patient-dashboard/chat'
    | '/patient-dashboard/documents'
    | '/patient-dashboard/settings'
    | '/patient-dashboard/'
    | '/patient-dashboard/acp/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doctor-dashboard'
    | '/doctor-dashboard/analytics'
    | '/doctor-dashboard/patients'
    | '/doctor-dashboard/reviews'
    | '/doctor-dashboard/settings'
    | '/patient-dashboard/chat'
    | '/patient-dashboard/documents'
    | '/patient-dashboard/settings'
    | '/patient-dashboard'
    | '/patient-dashboard/acp/$section'
  id:
    | '__root__'
    | '/'
    | '/doctor-dashboard'
    | '/patient-dashboard'
    | '/doctor-dashboard/analytics'
    | '/doctor-dashboard/patients'
    | '/doctor-dashboard/reviews'
    | '/doctor-dashboard/settings'
    | '/patient-dashboard/chat'
    | '/patient-dashboard/documents'
    | '/patient-dashboard/settings'
    | '/patient-dashboard/'
    | '/patient-dashboard/acp/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorDashboardRoute: typeof DoctorDashboardRouteWithChildren
  PatientDashboardRoute: typeof PatientDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient-dashboard': {
      id: '/patient-dashboard'
      path: '/patient-dashboard'
      fullPath: '/patient-dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-dashboard': {
      id: '/doctor-dashboard'
      path: '/doctor-dashboard'
      fullPath: '/doctor-dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-dashboard/': {
      id: '/patient-dashboard/'
      path: '/'
      fullPath: '/patient-dashboard/'
      preLoaderRoute: typeof PatientDashboardIndexRouteImport
      parentRoute: typeof PatientDashboardRoute
    }
    '/patient-dashboard/settings': {
      id: '/patient-dashboard/settings'
      path: '/settings'
      fullPath: '/patient-dashboard/settings'
      preLoaderRoute: typeof PatientDashboardSettingsRouteImport
      parentRoute: typeof PatientDashboardRoute
    }
    '/patient-dashboard/documents': {
      id: '/patient-dashboard/documents'
      path: '/documents'
      fullPath: '/patient-dashboard/documents'
      preLoaderRoute: typeof PatientDashboardDocumentsRouteImport
      parentRoute: typeof PatientDashboardRoute
    }
    '/patient-dashboard/chat': {
      id: '/patient-dashboard/chat'
      path: '/chat'
      fullPath: '/patient-dashboard/chat'
      preLoaderRoute: typeof PatientDashboardChatRouteImport
      parentRoute: typeof PatientDashboardRoute
    }
    '/doctor-dashboard/settings': {
      id: '/doctor-dashboard/settings'
      path: '/settings'
      fullPath: '/doctor-dashboard/settings'
      preLoaderRoute: typeof DoctorDashboardSettingsRouteImport
      parentRoute: typeof DoctorDashboardRoute
    }
    '/doctor-dashboard/reviews': {
      id: '/doctor-dashboard/reviews'
      path: '/reviews'
      fullPath: '/doctor-dashboard/reviews'
      preLoaderRoute: typeof DoctorDashboardReviewsRouteImport
      parentRoute: typeof DoctorDashboardRoute
    }
    '/doctor-dashboard/patients': {
      id: '/doctor-dashboard/patients'
      path: '/patients'
      fullPath: '/doctor-dashboard/patients'
      preLoaderRoute: typeof DoctorDashboardPatientsRouteImport
      parentRoute: typeof DoctorDashboardRoute
    }
    '/doctor-dashboard/analytics': {
      id: '/doctor-dashboard/analytics'
      path: '/analytics'
      fullPath: '/doctor-dashboard/analytics'
      preLoaderRoute: typeof DoctorDashboardAnalyticsRouteImport
      parentRoute: typeof DoctorDashboardRoute
    }
    '/patient-dashboard/acp/$section': {
      id: '/patient-dashboard/acp/$section'
      path: '/acp/$section'
      fullPath: '/patient-dashboard/acp/$section'
      preLoaderRoute: typeof PatientDashboardAcpSectionRouteImport
      parentRoute: typeof PatientDashboardRoute
    }
  }
}

interface DoctorDashboardRouteChildren {
  DoctorDashboardAnalyticsRoute: typeof DoctorDashboardAnalyticsRoute
  DoctorDashboardPatientsRoute: typeof DoctorDashboardPatientsRoute
  DoctorDashboardReviewsRoute: typeof DoctorDashboardReviewsRoute
  DoctorDashboardSettingsRoute: typeof DoctorDashboardSettingsRoute
}

const DoctorDashboardRouteChildren: DoctorDashboardRouteChildren = {
  DoctorDashboardAnalyticsRoute: DoctorDashboardAnalyticsRoute,
  DoctorDashboardPatientsRoute: DoctorDashboardPatientsRoute,
  DoctorDashboardReviewsRoute: DoctorDashboardReviewsRoute,
  DoctorDashboardSettingsRoute: DoctorDashboardSettingsRoute,
}

const DoctorDashboardRouteWithChildren = DoctorDashboardRoute._addFileChildren(
  DoctorDashboardRouteChildren,
)

interface PatientDashboardRouteChildren {
  PatientDashboardChatRoute: typeof PatientDashboardChatRoute
  PatientDashboardDocumentsRoute: typeof PatientDashboardDocumentsRoute
  PatientDashboardSettingsRoute: typeof PatientDashboardSettingsRoute
  PatientDashboardIndexRoute: typeof PatientDashboardIndexRoute
  PatientDashboardAcpSectionRoute: typeof PatientDashboardAcpSectionRoute
}

const PatientDashboardRouteChildren: PatientDashboardRouteChildren = {
  PatientDashboardChatRoute: PatientDashboardChatRoute,
  PatientDashboardDocumentsRoute: PatientDashboardDocumentsRoute,
  PatientDashboardSettingsRoute: PatientDashboardSettingsRoute,
  PatientDashboardIndexRoute: PatientDashboardIndexRoute,
  PatientDashboardAcpSectionRoute: PatientDashboardAcpSectionRoute,
}

const PatientDashboardRouteWithChildren =
  PatientDashboardRoute._addFileChildren(PatientDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorDashboardRoute: DoctorDashboardRouteWithChildren,
  PatientDashboardRoute: PatientDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
